# Generated by Django 3.2.8 on 2021-11-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20211103_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='---', max_length=100, verbose_name='Idioma'),
            preserve_default=False,
        ),
    ]
